export const GET_BLOG_REQUEST = 'GET_BLOG_REQUEST';
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS';
export const GET_BLOG_FAILED = 'GET_BLOG_FAILED';

export const REMOVE_BLOG_REQUEST = 'REMOVE_BLOG_REQUEST';
export const REMOVE_BLOG_SUCCESS = 'REMOVE_BLOG_SUCCESS';
export const REMOVE_BLOG_FAILED = 'REMOVE_BLOG_FAILED';

export const COMMENT_REQUEST = 'COMMENT_REQUEST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILED = 'COMMENT_FAILED';

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED';

export const USER_LOGOUT = 'USER_LOGOUT';